---
- name: Monitor disk usage and send alerts
  hosts: all
  become: yes
  tasks:
    - name: Check disk usage
      ansible.builtin.command: df -h /
      register: disk_usage

    - name: Extract disk usage percentage
      ansible.builtin.set_fact:
        usage_percent: "{{ disk_usage.stdout_lines[1].split()[4] | regex_replace('%', '') | int }}"

    - name: Display disk usage
      ansible.builtin.debug:
        msg: "Current disk usage: {{ usage_percent }}%"

    - name: Send alert if disk usage exceeds threshold
      ansible.builtin.fail:
        msg: "Disk usage is critically high: {{ usage_percent }}%"
      when: usage_percent > 80
