---
- name: Completely remove Nginx from system
  hosts: all
  become: true
  tasks:
    - name: Stop Nginx service if running
      systemd:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Uninstall Nginx (YUM)
      yum:
        name: nginx
        state: absent

    - name: Uninstall Nginx (DNF)
      dnf:
        name: nginx
        state: absent
      when: ansible_pkg_mgr == "dnf"

    - name: Remove Nginx directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx
        - /var/log/nginx
        - /var/cache/nginx
        - /usr/lib/nginx
        - /usr/share/nginx

    - name: Remove systemd service files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/lib/systemd/system/nginx.service
        - /lib/systemd/system/nginx.service

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Verify Nginx removal
      command: "find / -name '*nginx*' -type d"
      register: nginx_removal_check

    - name: Display remaining Nginx-related directories
      debug:
        msg: "{{ nginx_removal_check.stdout_lines }}"
